name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python/Node.js
        uses: actions/setup-python@v4  # or actions/setup-node@v3 for Node.js
        with:
          python-version: '3.9'  # or node-version: '16'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # or npm install for Node.js

      - name: Run tests
        run: |
          python -m pytest  # or npm test for Node.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to AWS/Azure/GCP
        run: |
          # Add deployment scripts here
          echo "Deploying to cloud..."